### ISSUE TITLE
2168-0002 when adding 0x10 to the pointer of stale[0]

### ISSUE THREAD

**Issue by username010** [LiveOverflow/lo_nintendoswitch#1]
my switch always crashes with 2168-0002 when getting to this [line](https://github.com/LiveOverflow/lo_nintendoswitch/blob/master/poc1.html#L167)
i assume you were able to amend the size of `smash` with this code. So i am wondering if my setup is somehow different? Does it always work for you without crashing?

**Comment by LiveOverflow** [comment]
Which web applet are you using? I'm redirecting the conntest.nintendowifi.net request. For example when connecting to the wifi or checking for a Game Update. I have heard that the web browser used for twitter/facebook or the eshop are weird.

**Comment by username010** [comment]
yay, thanks for your help, i've managed to run this 👍 the problem was that i was running it via web browser :)
