### ISSUE TITLE
Search for 0x41414242 looks into same index

### ISSUE THREAD

**Issue by KammererTob** [LiveOverflow/lo_nintendoswitch#2]
Not sure if a bug or intentional, but i noticed that your nested loop does not work correctly on the search for the changed Integer:

```
 for (i = 0; i < bufs.length; i++) {
     for (k = 0; k < bufs[0].length; k++) {
```
https://github.com/LiveOverflow/lo_nintendoswitch/blob/master/poc1.html#L144-L145

**Comment by LiveOverflow** [comment]
It's a bit ugly code, but it doesn't matter. All arrays in `buf[i]` have the same length. So you can reuse the length from `buf[0]`.

**Comment by KammererTob** [comment]
Ah. Quite right. Did not think of that..
